# site settings
title: Container
subtitle: The PHP League
email: mail@philbennett.co.uk
description: A simple but powerful PSR-11 dependency injection container
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-count: 4

# social settings
github_url: https://github.com/thephpleague/container
slack_url: https://thephpleague.slack.com

# build settings
markdown: kramdown
highlighter: rouge

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
