name: Tests

on:
    push: ~
    pull_request: ~

jobs:
    cs:
        name: Coding Standards
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2

            - run: composer update --no-progress
            - run: vendor/bin/php-cs-fixer fix --dry-run --diff

    tests:
        name: Tests on PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.3', '8.4', '8.5']
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, mbstring
                  coverage: ${{ matrix.php == '8.4' && 'pcov' || 'none' }}
                  tools: composer:v2

            - run: composer update --no-progress

            - run: vendor/bin/pest --coverage-clover=coverage.clover
              if: matrix.php == '8.4'

            - run: vendor/bin/pest
              if: matrix.php != '8.4'

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2

            - run: composer update --no-progress
            - run: vendor/bin/phpstan analyse --no-progress
